// <auto-generated />
namespace SolidProject.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PK001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PK001));
        
        string IMigrationMetadata.Id
        {
            get { return "201807130957031_PK001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
